apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Release.Name }}-control-plane
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.KubeadmControlPlane.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          systemd:
            {{- if .Values.flatcarUpdate.enable  }}
            files:
            - path: /etc/flatcar/update.conf
              filesystem: root
              mode: 0644
              contents:
                inline: |
                  GROUP=stable
                  SERVER={{ .Values.flatcarUpdate.url }} 
            {{- end }}
            units:
            - name: coreos-metadata-sshkeys@.service
              enabled: true
            - name: kubeadm.service
              enabled: true
              dropins:
              - name: 10-flatcar.conf
                contents: |
                  [Unit]
                  Requires=containerd.service coreos-metadata.service
                  After=containerd.service coreos-metadata.service
                  [Service]
                  EnvironmentFile=/run/metadata/flatcar
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: ${COREOS_OPENSTACK_HOSTNAME}
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: ${COREOS_OPENSTACK_HOSTNAME}
    preKubeadmCommands:
    - export COREOS_OPENSTACK_HOSTNAME=${COREOS_OPENSTACK_HOSTNAME%.*}
    - envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp
    - mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: {{ .Release.Name }}-control-plane
  replicas: {{ .Values.controlPlaneReplicas }}
  version: {{ .Values.kuberentesVersion }}