apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: {{ .Release.Name }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.OpenStackCluster.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.externalRouter.enabled }}
  router:
    id: {{ .Values.externalRouter.id }}
  {{- end }}
  allowAllInClusterTraffic: {{ .Values.allowAllInClusterTraffic }}
  apiServerLoadBalancer:
    enabled: {{ .Values.apiServerLoadBalancer.enabled }}
  cloudName: {{ .Values.cloudName }}
  dnsNameservers:
  - ${OPENSTACK_DNS_NAMESERVERS}
  externalNetworkId: ${OPENSTACK_EXTERNAL_NETWORK_ID}
  identityRef:
    kind: Secret
    name: {{ .Values.cloudConfigSecretName }} 
  managedSecurityGroups: true
  nodeCidr: {{ .Values.nodeCidr }}