---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-control-plane
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.OpenStackMachineTemplate.controlPlane.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  template:
    spec:
      cloudName: {{ .Values.cloudName }}
      flavor: {{ .Values.controlPlaneMachineFlavour }}
      identityRef:
        kind: Secret
        name: {{ .Values.cloudConfigSecretName }} 
      image: {{ .Values.imageName }}
      sshKeyName: {{ .Values.sshKeyName}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-md-0
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.OpenStackMachineTemplate.nodeGroup.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  template:
    spec:
      cloudName: {{ .Values.cloudName }}
      flavor: {{ .Values.nodeMachineFlavour }}
      identityRef:
        kind: Secret
        name: {{ .Values.cloudConfigSecretName }} 
      image: {{ .Values.imageName }}
      sshKeyName: {{ .Values.sshKeyName}}

{{- range $v := .Values.extraNodeGroups }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: "{{ $.Release.Name }}-md-{{ $v.name }}"
  {{- with (mergeOverwrite (deepCopy $.Values.annotations) $v.OpenStackMachineTemplate.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  template:
    spec:
      cloudName: {{ $.Values.cloudName }}
      flavor: {{ $v.OpenStackMachineTemplate.nodeMachineFlavour }}
      identityRef:
        kind: Secret
        name: {{ $.Values.cloudConfigSecretName }}
      image: {{ $.Values.imageName }}
      sshKeyName: {{ $.Values.sshKeyName}}
{{- end }}