cloudConfigSecretName: default-cloud-config
cloudName: openstack
imageName: flatcar-stable-3374.2.5-kube-v1.26.3
sshKeyName: capo-default
nodeMachineFlavour: m1.large
nodeMachineReplicas: 1
nodeCidr: 10.6.0.0/24
controlPlaneMachineFlavour: m1.large
controlPlaneReplicas: 1
podsCidrBlocks:
  - 192.168.0.0/16
failureDomain: nova
dnsNameserver: 8.8.8.8
externalNetworkId: a046e116-11b4-4ad5-85a5-92f78c209df1
kuberentesVersion: v1.26.3
allowAllInClusterTraffic: true
apiServerLoadBalancer:
  enabled: true
flatcarUpdate:
  enable: true
  url: https://example.com/v1/update/  
externalRouter:
  enable: false
  id: b046e116-11b4-4ad5-85a5-92f78c209df1

annotations: {}

Cluster:
  annotations: {}
    # cluster-autoscaler: enable
KubeadmConfigTemplate:
  annotations: {}
KubeadmControlPlane:
  annotations: {}
MachineDeployment:
  annotations: {}
    # cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
    # cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
OpenStackCluster:
  annotations: {}
OpenStackMachineTemplate:
  controlPlane:
    annotations: {}
  nodeGroup:
    annotations: {}


extraNodeGroups: []
  # - name: another-group
  #   OpenStackMachineTemplate:
  #     annotations: {}
  #     nodeMachineFlavour: m1.large
  #   MachineDeployment:
  #     annotations: 
  #       cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
  #       cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"
  #       capacity.cluster-autoscaler.kubernetes.io/memory: "128G"
  #       capacity.cluster-autoscaler.kubernetes.io/cpu: "16"
  #       capacity.cluster-autoscaler.kubernetes.io/ephemeral-disk: "100Gi"
  #       capacity.cluster-autoscaler.kubernetes.io/maxPods: "200"
  #     nodeMachineReplicas: 1






